RedHatInsights/cloudwatch-aggregator

templates/cloudwatch-aggregator.yml

Tested the deploy here: https://console.insights-dev.openshift.com/console/project/zhzeng/browse/deployments
Get the yml files of each resource and run the linter, looks good

Fix validation error for cloudwatch aggregator

---

Pipfile
Pipfile.lock
build_deploy_sc.sh

This PR is to push Z-Stream security patches to the `main` branch from `security-compliance`

Applying Security Patching from 'security-compliance' to 'main'

---

templates/cloudwatch-aggregator.yml

Need to add the public port to the non-clowder deploy file

Add the public port to the non-clowder deploy

---

templates/clowdapp.yml

Not sure if this will fix anything, but we have these in place for other apps

Make sure parameters are in place for clowdapp

---

templates/clowdapp.yml

We may not need these and I think something is failing in the integration tester in app interface. Not sure this would be the problem, but giving it a try

fix(clowdapp): strip out some config lines

---

templates/clowdapp.yml

Went back through the podspec and compared it with the docs for clowder.

Rework the clowder config

---

build_deploy.sh

Store the docker config in a new tmp dir instead of the $WORKSPACE

Use temp dir for docker config

---

templates/cloudwatch-aggregator.yml

reduce the value for the memory limit and request based on long-term data

updated values for memory limit and request for cloudwatch aggregator

---

Dockerfile

[RHCLOUD-35388](https://issues.redhat.com/browse/RHCLOUD-35388)

[RHCLOUD-35388] migrate the base image to the ubi9

---

.tekton/cloudwatch-aggregator-pull-request.yaml
.tekton/cloudwatch-aggregator-push.yaml

Change "build source image" default variable from false to true as required by konflux migration

[KONFLUX] Update source variable

---

Pipfile
Pipfile.lock
requirements.txt

[RHCLOUD-36498](https://issues.redhat.com/browse/RHCLOUD-36498)

[RHCLOUD-36498] upgrade app-common-python package to the latest version

---

Pipfile
Pipfile.lock
requirements.txt

[RHCLOUD-36525](https://issues.redhat.com/browse/RHCLOUD-36525)

[RHCLOUD-36525] upgrade urllib3 to the 1.26.20

---

Pipfile.lock
requirements.txt

[RHCLOUD-36685](https://issues.redhat.com/browse/RHCLOUD-36685)

[RHCLOUD-36685] Lock the dependencies and regenerate the Pipfile.lock

---

Pipfile.lock
requirements.txt

[RHCLOUD-36824](https://issues.redhat.com/browse/RHCLOUD-36824)

[RHCLOUD-36824] lock pipenv file and regenerate the requirements.txt

---

.github/workflows/pre-commit.yml

[RHCLOUD-36901](https://issues.redhat.com/browse/RHCLOUD-36901)

[RHCLOUD-36901] add pre-commit github action into repo

---

.github/workflows/json-yaml-validation.yml
templates/cloudwatch-aggregator.yml

[RHCLOUD-37201](https://issues.redhat.com/browse/RHCLOUD-37201)
note:
in the second commit I removed 2 lines because it was a duplicity, check the file few lines above

[RHCLOUD-37201] add json and yaml basic validator into ci

---

Pipfile
Pipfile.lock
requirements.txt

[RHCLOUD-37556](https://issues.redhat.com/browse/RHCLOUD-37556)

[RHCLOUD-37556] update dependencies in pipfiles and requirements.txt

---

templates/cloudwatch-aggregator.yml

Update clowdapp.yaml to have the secretKeyRef to match with the key and name within the vault

Update splunk token to refer to key related to the key name in vault

---

Dockerfile

https://issues.redhat.com/browse/RHCLOUD-35388

RHCLOUD-35388 - ubi8 to ubi9 update

---

templates/cloudwatch-aggregator.yml

to solve the readiness and liveness probe timeouts in production
related with Slack discussion [here](https://redhat-internal.slack.com/archives/C023NSG08N7/p1748342394656819)

increase the timeout limit for readiness and liveness probe

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
Dockerfile
Pipfile
Pipfile.lock

[RHCLOUD-40364](https://issues.redhat.com/browse/RHCLOUD-40364)

[RHCLOUD-40364] upgrade to the python 3.12

---

.github/renovate.json

renovate docs: https://docs.renovatebot.com/configuration-options/#matchbasebranches
internal konflux docs: https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#available-managers
we need to disable creation of konflux-bot PRs for `security-compliance `branch

add renovate config file and disable dependency updates for security-compliance branch
